media:
  input: content/images
  output: ../images
  rename: random

content:
  - name: blog
    label: Blog
    type: collection
    path: content/blog
    delimiters: "---"
    filename:
      template: "{primary}.md"
      field: create
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
        options:
          format: "yyyy-MM-dd"
      - name: emoji
        label: Emoji
        type: string
        default: "🍜"
      - name: tags
        label: Tags
        type: string
        list: true
      - name: published
        label: Published
        type: boolean
        default: false
      - name: body
        label: Body
        type: rich-text
    actions:
      - name: deploy
        label: Deploy
        workflow: build.yml
  - name: pages
    label: Pages
    type: collection
    path: content/pages
    delimiters: "---"
    filename:
      template: "{primary}.md"
      field: create
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text

actions:
  - name: deploy
    label: Deploy
    workflow: build.yml